<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Book8.aspx.cs" Inherits="Book_Book8" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <div class="entry-header" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <div id="baikecard" data-sub="#1953729-2067635-0" style="margin: 0px; padding: 20px 30px 0px;">
            <div id="baike-title" style="margin: 10px 0px; padding: 0px; position: relative;">
                <h1 style="margin: 0px; padding: 0px; font-size: 12px; font-weight: 500;"><span class="title" style="color: rgb(51, 51, 51); font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; font-size: 30px; font-weight: 500; line-height: 34px; overflow: hidden; position: relative; z-index: 0;">高兴<span class="sense" style="color: rgb(119, 119, 119); font-size: 16px;"><span class="Apple-converted-space">&nbsp;</span>- 贾平凹小说</span></span><span class="Apple-converted-space">&nbsp;</span><span id="edit_op" class="opt js-edittext" style="margin-left: 15px;"><a id="J-entry-edit" class="edit edit-btn" href="https://baike.so.com/create/edit/?eid=1953729&amp;sid=2067635" style="color: rgb(49, 152, 24); text-decoration: none; display: inline-block; font-size: 14px;"><i class="ico" style="background-image: url(&quot;https://p.ssl.qhmsg.com/t01c067b7271a91a2e3.png&quot;); background-repeat: no-repeat; background-position: 0px -40px; display: inline-block; height: 13px; margin-right: 3px; vertical-align: -2px; width: 13px;"></i>免费编辑</a><span class="Apple-converted-space">&nbsp;</span></span><span class="opt" style="margin-left: 15px;"><a id="J-entry-sense" class="J-entry-sense" href="javascript:;" style="color: rgb(49, 152, 24); text-decoration: none; display: inline-block; font-size: 14px; font-family: arial, sans-serif;"><i class="ico" style="background-image: url(&quot;https://p.ssl.qhmsg.com/t013fe6605a5cb2fc1a.png&quot;); background-repeat: no-repeat; display: inline-block; height: 14px; margin-right: 3px; vertical-align: -3px; width: 15px;"></i>修改义项名</a></span></h1>
            </div>
            <div id="entry-classify" class="entry-classify " style="margin: 10px 0px; padding: 0px 10px 0px 0px; background-color: rgb(250, 250, 250); border: 1px solid rgb(230, 230, 230); color: rgb(102, 102, 102); font-family: &quot;microsoft yahei&quot;; height: 30px; line-height: 28px; text-indent: 8px;">
                <div class="entry-classify-hd" style="margin: 0px; padding: 0px; float: left; height: 30px; position: relative;">
                    <div class="entry-classify-down js-classify-list" style="margin: 0px; padding: 0px; background: rgb(250, 250, 250); overflow: hidden; position: absolute; user-select: none; width: 360px; z-index: 1;">
                        <span class="name" style="float: left;">所属类别 :</span><div class="classify-txt js-classify-txt short" style="margin: 4px 0px; padding: 0px 0px 0px 5px; display: inline-block; float: left; line-height: 22px; text-align: justify; text-indent: 0px; white-space: nowrap; width: 225px; word-wrap: normal;">
                            图书</div>
                    </div>
                </div>
                <div class="entry-classify-bd" style="margin: 0px; padding: 0px; float: right;">
                </div>
            </div>
            <div id="js-card-content" class="card_content" style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-size: 14px; line-height: 24px;">
                <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em;">
                    《高兴》是贾平凹创作的长篇小说，讲述了他对农民的一贯关注，写进了城的农民--城市中的拾荒人的命运。</p>
                <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em;">
                    作品采用口述体的第一人称，语言幽默，流畅，易于阅读， 小说中的人物都有一个共同的特点，都是在城市中艰难地生存。而且，作品在描述他们生活困境的同时，着重关注了他们的精神世界，写了他们的理想、追求和爱情。</p>
            </div>
            <div class="intro_button" style="margin: 0px; padding: 0px;">
            </div>
        </div>
        <div id="starVideo" class="starVideo starVideo1" style="margin: 0px 30px; padding: 0px;">
        </div>
    </div>
    <div id="entry-stream-switch" class="entry-stream-switch" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <div class="stream-switch-wrap" style="margin: 25px 0px 0px; padding: 0px 30px; background: rgb(250, 250, 250); border-bottom: rgb(245, 245, 245); height: 40px; position: relative;">
            <div class="switch-tag switch-word js-stream-switch active" data-module="entry-detail" data-switch="js-switch-word" style="margin: 0px; padding: 0px; cursor: pointer; float: left; line-height: 40px; position: relative; text-align: center; width: 100px; z-index: 1;">
                <span class="switch-tag-text" style="color: rgb(25, 185, 85); font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; font-size: 18px;">词条</span></div>
            <div class="switch-tag switch-plus js-stream-switch" data-module="entry-stream" data-switch="js-switch-plus" style="margin: 0px; padding: 0px; cursor: pointer; float: left; line-height: 40px; position: relative; text-align: center; width: 100px; z-index: 1;">
                <span class="switch-tag-text" style="color: rgb(180, 180, 180); font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; font-size: 18px;">百科</span><i class="tag-icon" style="background: url(&quot;https://p.ssl.qhmsg.com/t0101facb44b94934c8.png&quot;) 0px 0px no-repeat; color: rgb(247, 189, 75); display: block; font-weight: 700; height: 8px; position: absolute; right: 21px; top: 12px; width: 8px;"></i><div class="stream-function-tip js-stream-tips active" style="margin: 0px; padding: 0px; background: url(&quot;https://p.ssl.qhmsg.com/t01cf22e16e88680a2d.png&quot;) 0px 0px no-repeat; display: block; height: 50px; left: 83px; position: absolute; top: -25px; width: 170px;">
                    <span class="function-tip-text" style="color: rgb(25, 185, 85); font-size: 14px; height: 40px; left: 35px; line-height: 40px; position: absolute; top: 2px;">精彩信息一览无遗</span></div>
            </div>
            <i class="stream-switch-bar js-stream-bar" style="border-bottom: 3px solid rgb(25, 185, 85); height: 37px; left: 70px; position: absolute; width: 20px;"></i>
        </div>
    </div>
    <div class="entry-detail" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <div class="entry-basic" style="margin: 0px; padding: 0px;">
            <div id="basic-info" style="margin: 25px 30px 0px; padding: 0px;">
                <a name="uni_baseinfo" style="color: rgb(19, 110, 194); text-decoration: none;"></a>
                <h2 class="titleH2" style="margin: 0px; padding: 20px 0px 5px; font-size: 24px; font-weight: 500; font-style: normal; font-variant: normal; font-stretch: normal; line-height: 22px; font-family: &quot;microsoft yahei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;"><span class="h2mark" style="background: rgb(55, 171, 47); display: block; font-size: 0px; height: 24px; line-height: 0; margin: 0px 0px 0px -30px; padding: 0px; position: absolute; width: 10px;"></span>基本信息</h2>
                <div class="card-list-box" style="margin: 10px 0px; padding: 0px; border-top: 1px solid rgb(230, 230, 230); border-bottom: 1px solid rgb(230, 230, 230); font-size: 0px;">
                    <ul class="cardlist" style="margin: 0px 0px -1px; padding: 0px; list-style: none; display: inline-block; vertical-align: text-top; width: 403.5px;">
                        <li style="margin: 0px; padding: 0px 0px 0px 100px; background: rgb(245, 245, 245); border-bottom: 1px solid rgb(238, 238, 238);">
                            <div class="cardlist-con" style="margin: 0px; padding: 0px; background: rgb(255, 255, 255); position: relative;">
                                <p class="cardlist-name" style="margin: 0px 0px 0px -100px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: inline; float: left; width: 100px; word-wrap: normal; outline: 0px !important;" title="书名">
                                    书名</p>
                                <p class="cardlist-value" style="margin: 0px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: block; width: 303.5px;" title="高兴">
                                    高兴</p>
                            </div>
                        </li>
                        <li style="margin: 0px; padding: 0px 0px 0px 100px; background: rgb(245, 245, 245); border-bottom: 1px solid rgb(238, 238, 238);">
                            <div class="cardlist-con" style="margin: 0px; padding: 0px; background: rgb(255, 255, 255); position: relative;">
                                <p class="cardlist-name" style="margin: 0px 0px 0px -100px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: inline; float: left; width: 100px; word-wrap: normal; outline: 0px !important;" title="定价">
                                    定价</p>
                                <p class="cardlist-value" style="margin: 0px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: block; width: 303.5px;" title="28.00">
                                    28.00</p>
                            </div>
                        </li>
                        <li style="margin: 0px; padding: 0px 0px 0px 100px; background: rgb(245, 245, 245); border-bottom: 1px solid rgb(238, 238, 238);">
                            <div class="cardlist-con" style="margin: 0px; padding: 0px; background: rgb(255, 255, 255); position: relative;">
                                <p class="cardlist-name" style="margin: 0px 0px 0px -100px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: inline; float: left; width: 100px; word-wrap: normal; outline: 0px !important;" title="出版社">
                                    出版社</p>
                                <p class="cardlist-value" style="margin: 0px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: block; width: 303.5px;" title="漓江出版社">
                                    漓江出版社</p>
                            </div>
                        </li>
                        <li style="margin: 0px; padding: 0px 0px 0px 100px; background: rgb(245, 245, 245); border-bottom: 1px solid rgb(238, 238, 238);">
                            <div class="cardlist-con" style="margin: 0px; padding: 0px; background: rgb(255, 255, 255); position: relative;">
                                <p class="cardlist-name" style="margin: 0px 0px 0px -100px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: inline; float: left; width: 100px; word-wrap: normal; outline: 0px !important;" title="作者">
                                    作者</p>
                                <p class="cardlist-value" style="margin: 0px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: block; width: 303.5px;" title="贾平凹">
                                    贾平凹</p>
                            </div>
                        </li>
                    </ul>
                    <span class="Apple-converted-space">&nbsp;</span><ul class="cardlist" style="margin: 0px 0px -1px; padding: 0px; list-style: none; display: inline-block; vertical-align: text-top; width: 403.5px;">
                        <li style="margin: 0px; padding: 0px 0px 0px 100px; background: rgb(245, 245, 245); border-bottom: 1px solid rgb(238, 238, 238);">
                            <div class="cardlist-con" style="margin: 0px; padding: 0px; background: rgb(255, 255, 255); position: relative;">
                                <p class="cardlist-name" style="margin: 0px 0px 0px -100px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: inline; float: left; width: 100px; word-wrap: normal; outline: 0px !important;" title="出版时间">
                                    出版时间</p>
                                <p class="cardlist-value" style="margin: 0px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: block; width: 303.5px;" title="2012-8-1">
                                    2012-8-1</p>
                            </div>
                        </li>
                        <li style="margin: 0px; padding: 0px 0px 0px 100px; background: rgb(245, 245, 245); border-bottom: 1px solid rgb(238, 238, 238);">
                            <div class="cardlist-con" style="margin: 0px; padding: 0px; background: rgb(255, 255, 255); position: relative;">
                                <p class="cardlist-name" style="margin: 0px 0px 0px -100px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: inline; float: left; width: 100px; word-wrap: normal; outline: 0px !important;" title="装帧">
                                    装帧</p>
                                <p class="cardlist-value" style="margin: 0px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: block; width: 303.5px;" title="平装">
                                    平装</p>
                            </div>
                        </li>
                        <li style="margin: 0px; padding: 0px 0px 0px 100px; background: rgb(245, 245, 245); border-bottom: 1px solid rgb(238, 238, 238);">
                            <div class="cardlist-con" style="margin: 0px; padding: 0px; background: rgb(255, 255, 255); position: relative;">
                                <p class="cardlist-name" style="margin: 0px 0px 0px -100px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: inline; float: left; width: 100px; word-wrap: normal; outline: 0px !important;" title="ISBN">
                                    ISBN</p>
                                <p class="cardlist-value" style="margin: 0px; padding: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 12px; line-height: 28px; font-family: Arial, sans-serif; overflow: hidden; text-indent: 10px; text-overflow: ellipsis; white-space: nowrap; display: block; width: 303.5px;" title="9787540758011">
                                    9787540758011</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="entry-before" style="margin: 0px; padding: 0px;">
        </div>
        <div class="entry-catalogue" style="margin: 0px; padding: 0px;">
            <div class="entry-mod-catalogue" style="margin: 0px; padding: 0px 30px;">
                <div class="catalogModWrap" style="margin: 30px 0px; padding: 0px;">
                    <span class="h2mark" style="background: rgb(55, 171, 47); display: block; font-size: 0px; height: 24px; line-height: 0; margin: 0px 0px 0px -30px; padding: 0px; position: absolute; width: 10px;"></span>
                    <table id="J-ext-mod-topcatalog" class="catalogMod" style="border-collapse: collapse; border-spacing: 0px; border: 1px solid rgb(229, 229, 229); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 18px; line-height: 1.5; font-family: &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; width: 806px;">
                        <tr>
                            <th style="margin: 0px; padding: 0px; text-align: center; font-style: normal; background: rgb(244, 244, 244); color: rgb(34, 34, 34); font-weight: 400; width: 80px;"><span style="display: block;">目录</span></th>
                            <td class="listTd" style="margin: 0px; padding: 14px 15px 14px 5px; vertical-align: top; border-left: 1px solid rgb(229, 229, 229);">
                                <div style="margin: 0px; padding: 1px 0px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; width: 180px; word-wrap: normal; outline: 0px !important;">
                                    <em style="font-style: normal; color: rgb(159, 157, 157); display: inline-block; font-weight: 400; font-family: Arial, sans-serif; margin-right: 5px; text-align: right; width: 20px;">1</em><a href="https://baike.so.com/doc/1953729-2067635.html#1953729-2067635-1" style="color: rgb(85, 85, 85); text-decoration: none;" title="内容梗概">内容梗概</a></div>
                                <div style="margin: 0px; padding: 1px 0px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; width: 180px; word-wrap: normal; outline: 0px !important;">
                                    <em style="font-style: normal; color: rgb(159, 157, 157); display: inline-block; font-weight: 400; font-family: Arial, sans-serif; margin-right: 5px; text-align: right; width: 20px;">2</em><a href="https://baike.so.com/doc/1953729-2067635.html#1953729-2067635-2" style="color: rgb(85, 85, 85); text-decoration: none;" title="创作历程">创作历程</a></div>
                                <div style="margin: 0px; padding: 1px 0px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; width: 180px; word-wrap: normal; outline: 0px !important;">
                                    <em style="font-style: normal; color: rgb(159, 157, 157); display: inline-block; font-weight: 400; font-family: Arial, sans-serif; margin-right: 5px; text-align: right; width: 20px;">3</em><a href="https://baike.so.com/doc/1953729-2067635.html#1953729-2067635-3" style="color: rgb(85, 85, 85); text-decoration: none;" title="主要人物">主要人物</a></div>
                            </td>
                            <td class="listTd" style="margin: 0px; padding: 14px 15px 14px 5px; vertical-align: top; border-left: 1px solid rgb(229, 229, 229);">
                                <div style="margin: 0px; padding: 1px 0px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; width: 180px; word-wrap: normal; outline: 0px !important;">
                                    <em style="font-style: normal; color: rgb(159, 157, 157); display: inline-block; font-weight: 400; font-family: Arial, sans-serif; margin-right: 5px; text-align: right; width: 20px;">4</em><a href="https://baike.so.com/doc/1953729-2067635.html#1953729-2067635-4" style="color: rgb(85, 85, 85); text-decoration: none;" title="作品赏析">作品赏析</a></div>
                                <div style="margin: 0px; padding: 1px 0px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; width: 180px; word-wrap: normal; outline: 0px !important;">
                                    <em style="font-style: normal; color: rgb(159, 157, 157); display: inline-block; font-weight: 400; font-family: Arial, sans-serif; margin-right: 5px; text-align: right; width: 20px;">5</em><a href="https://baike.so.com/doc/1953729-2067635.html#1953729-2067635-5" style="color: rgb(85, 85, 85); text-decoration: none;" title="作品评价">作品评价</a></div>
                                <div style="margin: 0px; padding: 1px 0px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; width: 180px; word-wrap: normal; outline: 0px !important;">
                                    <em style="font-style: normal; color: rgb(159, 157, 157); display: inline-block; font-weight: 400; font-family: Arial, sans-serif; margin-right: 5px; text-align: right; width: 20px;">6</em><a href="https://baike.so.com/doc/1953729-2067635.html#1953729-2067635-6" style="color: rgb(85, 85, 85); text-decoration: none;" title="作品影响">作品影响</a></div>
                            </td>
                            <td class="listTd" style="margin: 0px; padding: 14px 15px 14px 5px; vertical-align: top; border-left: 1px solid rgb(229, 229, 229);">
                                <div style="margin: 0px; padding: 1px 0px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; width: 180px; word-wrap: normal; outline: 0px !important;">
                                    <em style="font-style: normal; color: rgb(159, 157, 157); display: inline-block; font-weight: 400; font-family: Arial, sans-serif; margin-right: 5px; text-align: right; width: 20px;">7</em><a href="https://baike.so.com/doc/1953729-2067635.html#1953729-2067635-7" style="color: rgb(85, 85, 85); text-decoration: none;" title="作者简介">作者简介</a></div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="entry-body" style="margin: 0px; padding: 0px;">
        </div>
        <div class="entry-content" style="margin: 0px; padding: 0px;">
            <div id="lemma-main" class="lemma-meaning" data-sub="#1953729-2067635-0" style="margin: 0px 0px 15px; padding: 0px 30px; font-size: 14px; line-height: 28px; position: relative;">
                <div id="main-content-text" class="main_content_text cl" style="margin: 0px; padding: 0px; zoom: 1; word-wrap: break-word;">
                    <h2 style="margin: 35px 0px 15px -30px; padding: 0px; font-size: 22px; font-weight: 500; border-left: 10px solid rgb(55, 171, 47); line-height: 22px; text-indent: 20px; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative;"><a name="1953729-2067635-1" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h2-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><span class="opt js-edittext" style="border-right: 1px solid rgb(217, 217, 217); float: right; font-size: 12px; font-family: simsun; margin-right: 6px; padding-right: 7px;"><a class="edit" data-log="edit-title" href="https://baike.so.com/create/edit/?eid=1953729&amp;sid=2067635&amp;secid=1" style="color: rgb(49, 152, 24); text-decoration: none;"><i class="ico" style="font-style: italic; background-image: url(&quot;https://p.ssl.qhmsg.com/t01c067b7271a91a2e3.png&quot;); background-repeat: no-repeat; display: inline-block; height: 16px; vertical-align: -5px; width: 16px; background-position: 0px -40px;"></i>编辑本段</a></span><b class="title" style="font-weight: 500; color: rgb(0, 0, 0); float: left; font-size: 22px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; line-height: 24px; zoom: 1;">内容梗概</b></h2>
                    <div class="sonConBox " style="margin: 0px; padding: 0px; color: rgb(51, 51, 51);">
                        <div class="h2_content" style="margin: 0px; padding: 0px;">
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                <a class="show-img layoutright" data-index="1" data-type="gallery" href="https://p1.ssl.qhmsg.com/t01353d67bcbd255afe.jpg" style="color: rgb(0, 0, 0); text-decoration: none; background: rgb(250, 250, 250); display: inline-block; clear: both; font-size: 12px; margin: 5px 5px 5px 22px; overflow: hidden; text-align: center; text-indent: 0px; float: right;"><span class="show-img-hd" style="border-top: 1px solid rgb(229, 229, 229); border-right: 1px solid rgb(229, 229, 229); border-left: 1px solid rgb(229, 229, 229); border-image: initial; border-bottom: none; display: block; width: 220px; height: 220px;">
                                <img id="img_10998092" alt="高兴" data-img="mod_img" src="https://p1.ssl.qhmsg.com/dr/220__/t01353d67bcbd255afe.jpg" style="border: 0px; vertical-align: middle; width: 220px; height: 220px; display: inline;" title="高兴" /></span><span class="show-img-bd" style="border-right: 1px solid rgb(229, 229, 229); border-bottom: 1px solid rgb(229, 229, 229); border-left: 1px solid rgb(229, 229, 229); border-image: initial; border-top: none; display: block; line-height: 28px; overflow: hidden; padding: 0px 10px; text-align: left; width: 200px;">高兴</span></a>正当百事瓦裂、浮华猖獗的社会变改之际，农民刘高兴先是将自己的一颗肾卖给了城里人，随后来到城里拾破烂，妓女孟夷纯的出现不但引来了城市万象之态，还带给了他们支离纷崩、始料不及的命运。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                刘高兴来到大城市中，孤身一人，什么都不会，到处流离失所，靠着捡垃圾勉强度日，在捡垃圾的行当中认识了同乡五福，两人互相帮助，生活勉强有了好转，可是五福不幸车祸去世，这就更给刘高兴沉重的打击。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                刘高兴想尽一切办法试图将同乡五富的尸体运回清风镇，在火车站被警察拦截而未果始，以刘高兴将五富的尸体运回老家，等待五富的老婆等人，和他们一起料理五<a class="reference_sup" href="https://baike.so.com/doc/1953729-2067635.html#refff_1953729-2067635-1" name="refer_1953729-2067635-5390645" style="color: rgb(51, 102, 204); text-decoration: none; cursor: pointer; font-size: 12px; margin-left: 2px; padding: 0px 2px; position: relative; top: -0.5em; vertical-align: baseline; white-space: nowrap;">[1]</a>富后事终。和大多数农民一样，他们进城后的生活是格外艰辛的。他们带着寻找新家园的美好愿望和对新生活的憧憬来到城市，试图通过脱离农村和土地、走进大城市来改变他们的命运。可现实和理想往往反差很大，他们没有资金、没受过高等教育、没有技术、没有所谓的&quot;后门&quot;，想寻一份工作谈何容易，最后他们只能选择做最脏最累最没有社会地位的工作--拾破烂。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                刘高兴成为一名拾荒者以后，刘高兴和五富对这样的生活和这样的工作非常失望，但这已经是在同乡韩大宝的帮助下了，若是没有韩大宝的帮助，他们的境遇将更加无法想象。拾破烂的生活是艰辛而屈辱的，每天早晨，刘高兴和五富都拉着一辆破架子车，到固定的街道去拾破烂，无论严寒酷暑的穿街走巷。他们身上穿的都是拾破烂得来的衣服、鞋子，很多生活用具也是拾来的，包括做饭的锅灶。辛苦一天，早出晚归的，也只能赚个一二十元，连维持基本的生计都很难。他们住在两间简易房屋里，条件很差，但是房租便宜。一天中只有晚上才能吃上热饭菜，白天都是胡乱充饥，有时甚至吃路边拾来的发霉馒头。平日里他们吃的都是蒸馍、包谷糁和面糊糊疙瘩汤，连面条都很少吃到，在阴雨天出不了门就吃些少盐没醋的饭，吃顿羊肉泡馍这种好饭菜是件非常奢侈的事。他们想去公园逛逛却舍不得买门票，即使生了病因为怕花钱也不去看医生。</p>
                        </div>
                    </div>
                    <h2 style="margin: 35px 0px 15px -30px; padding: 0px; font-size: 22px; font-weight: 500; border-left: 10px solid rgb(55, 171, 47); line-height: 22px; text-indent: 20px; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative;"><a name="1953729-2067635-2" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h2-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><span class="opt js-edittext" style="border-right: 1px solid rgb(217, 217, 217); float: right; font-size: 12px; font-family: simsun; margin-right: 6px; padding-right: 7px;"><a class="edit" data-log="edit-title" href="https://baike.so.com/create/edit/?eid=1953729&amp;sid=2067635&amp;secid=2" style="color: rgb(49, 152, 24); text-decoration: none;"><i class="ico" style="font-style: italic; background-image: url(&quot;https://p.ssl.qhmsg.com/t01c067b7271a91a2e3.png&quot;); background-repeat: no-repeat; display: inline-block; height: 16px; vertical-align: -5px; width: 16px; background-position: 0px -40px;"></i>编辑本段</a></span><b class="title" style="font-weight: 500; color: rgb(0, 0, 0); float: left; font-size: 22px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; line-height: 24px; zoom: 1;">创作历程</b></h2>
                    <div class="sonConBox " style="margin: 0px; padding: 0px; color: rgb(51, 51, 51);">
                        <div class="h2_content" style="margin: 0px; padding: 0px;">
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                小说中的这两个人物都在生活中确有其人。刘高兴是贾平凹老家丹凤县棣花镇同村的伙伴，从小学到中学的同学。贾平凹大学毕业后就留在西安当了文学编辑，后来成为作家。而&quot;刘高兴&quot;当兵复员后回到农村，做过泥瓦匠、吊过挂面、磨过豆腐、摆过油条摊子，什么都没干出名堂，年过半百只好进城打工，拾破烂、给人送煤。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                通过自身的经历并酝酿成熟了文稿，并为了更好地写作这群都市边缘人的生存状态，贾平凹不断地到西安一个&quot;拾荒村&quot;去调查采访。这个村子全是来自农村，在城市里拾荒的农民。贾平凹和他们一起体验拾荒生活，还跟他们同吃同喝。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                在创作之初，《高兴》只有20多万字，但前后修改了五次，每改一次就要重新抄写一遍，因此书写总和就超过了100万字。贾平凹为写此书右手中指已经严重变形，不仅磨出了一个大坑，皮下还有淤血。</p>
                        </div>
                    </div>
                    <h2 style="margin: 35px 0px 15px -30px; padding: 0px; font-size: 22px; font-weight: 500; border-left: 10px solid rgb(55, 171, 47); line-height: 22px; text-indent: 20px; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative;"><a name="1953729-2067635-3" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h2-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><span class="opt js-edittext" style="border-right: 1px solid rgb(217, 217, 217); float: right; font-size: 12px; font-family: simsun; margin-right: 6px; padding-right: 7px;"><a class="edit" data-log="edit-title" href="https://baike.so.com/create/edit/?eid=1953729&amp;sid=2067635&amp;secid=3" style="color: rgb(49, 152, 24); text-decoration: none;"><i class="ico" style="font-style: italic; background-image: url(&quot;https://p.ssl.qhmsg.com/t01c067b7271a91a2e3.png&quot;); background-repeat: no-repeat; display: inline-block; height: 16px; vertical-align: -5px; width: 16px; background-position: 0px -40px;"></i>编辑本段</a></span><b class="title" style="font-weight: 500; color: rgb(0, 0, 0); float: left; font-size: 22px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; line-height: 24px; zoom: 1;">主要人物</b></h2>
                    <div class="sonConBox " style="margin: 0px; padding: 0px; color: rgb(51, 51, 51);">
                        <div class="h2_content" style="margin: 0px; padding: 0px;">
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                <strong style="font-weight: 700;">刘高兴</strong></p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                主人公刘高兴真有其人，为人大方，但却做事胆小，没什么大的抱负，只想着平凡的过好每一天，但现实总是不如人意他的生活可以用糟糕透顶不形容。刘高兴原名叫刘书祯，是贾平凹老家丹凤县棣花镇同村的伙伴，刘高兴当年当兵复员后回村继续当农民，迫于生计在年过半百时领着儿子进城打工，找不到工作就在西安以拾破烂维持生计。虽然生活艰辛，但他却很乐观、幽默，他给自己重新起名叫刘高兴。他每天就是在城市中捡垃圾，后来与同乡五福相识，在捡垃圾的过程中互相帮助，后来就成为了好兄弟，但是最后五福却因车祸死去，刘高兴只有一个人孤零零的在城市中捡垃圾了，生活也是越过越苦，最后人活着却如行尸走肉一般了。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                <strong style="font-weight: 700;">五富</strong></p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                在城市中靠捡破烂的流浪人，后来遇到刘高兴，与其认识后便一起合住在一起捡垃圾，或是做其他的劳动工作，为人没什么主见，而且还十分邋遢，总是受到刘高兴的帮助。但是总算是 还讲义气，在刘高兴被警察抓去的时候，自己挺身而出，帮助高兴免受牢狱之苦。但最终五福因车祸而死去。</p>
                        </div>
                    </div>
                    <h2 style="margin: 35px 0px 15px -30px; padding: 0px; font-size: 22px; font-weight: 500; border-left: 10px solid rgb(55, 171, 47); line-height: 22px; text-indent: 20px; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative;"><a name="1953729-2067635-4" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h2-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><span class="opt js-edittext" style="border-right: 1px solid rgb(217, 217, 217); float: right; font-size: 12px; font-family: simsun; margin-right: 6px; padding-right: 7px;"><a class="edit" data-log="edit-title" href="https://baike.so.com/create/edit/?eid=1953729&amp;sid=2067635&amp;secid=4" style="color: rgb(49, 152, 24); text-decoration: none;"><i class="ico" style="font-style: italic; background-image: url(&quot;https://p.ssl.qhmsg.com/t01c067b7271a91a2e3.png&quot;); background-repeat: no-repeat; display: inline-block; height: 16px; vertical-align: -5px; width: 16px; background-position: 0px -40px;"></i>编辑本段</a></span><b class="title" style="font-weight: 500; color: rgb(0, 0, 0); float: left; font-size: 22px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; line-height: 24px; zoom: 1;">作品赏析</b></h2>
                    <div class="sonConBox " style="margin: 0px; padding: 0px; color: rgb(51, 51, 51);">
                        <h3 style="margin: 20px 0px 12px; padding: 0px 0px 12px; font-size: 14px; font-weight: 500; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative; border-bottom: 1px solid rgb(236, 236, 236); cursor: pointer; line-height: 18px; overflow: hidden;"><a class="anchor" name="1953729-2067635-4_1" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h3-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><b class="title" style="font-weight: 500; color: rgb(51, 51, 51); float: left; font-size: 18px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif;">主题思想</b></h3>
                        <div class="h3_content" style="margin: 0px; padding: 0px;">
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                《高兴》不只是反映了拾荒的农民工的生活状态，更反映出整个西安城里各行各业的农民打工者的生存现实，它是一幅描绘农民进城务工的生活图卷。农民工为了自己的生活，同样为了城市建设在城市的角落里默默贡献着自己的力量。就像刘高兴说的:&quot;如果没有那些环卫工和我们，西安将会是个什么样子，&quot;这是我们这些城里人所无法想象的。但城市又是如何对待这些农民工的，他们总是怀着一颗虔诚又憧憬的心，渴望在城市生根立足，渴望这极具吸引力的宝地能有他们的容身之处，但他们却总是受到极不公平的对待。很多人都像刘高兴和五富一样，他们的身心被城市伤害得支离破碎。农民工们不仅付出了辛勤劳动，同时还有尊严，甚至生命。即使是这样的境遇。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                高兴的故事性很强，故事节奏也相对较快。但这部名叫高兴的小说，却经历了一个痛苦的酝酿的过程。贾平凹在后记里说这是他写得最吃力的一部小说。刘高兴是农村人，进城拾荒，一心想做城里人，举手投足，心里身外，做足了脱胎换骨的准备。最绝的是，他把肾卖给了城里人。肾是先天之本，主发育、生长、生殖，现在农民给城里生娃哩。他以为买肾的是韦达(伟哥)是有钱人，在一次抢劫中，两人不期而遇。从此，韦达成了刘高兴在城里的影子，成了他能留在城里的根，成了他梦幻的未来。在刘高兴看来，肾是认得路的，装在韦达身体里的一个肾，和装在自己身体里的一个肾，同时向孟夷纯靠拢。所以，孟夷纯和韦达的关系，并没有引起高兴的醋意，反倒让他有几分欣慰。然而，他错了。韦达并没有换肾，而是换肝，他失望了。一切都变了，不仅韦达与刘高兴失去了纽带，刘高兴做城里人的根，失去了具体可感的土，而且肾与肝大不相同，肾是先天之本，肝是后天之本。所以，当孟夷纯被抓，换肝的韦达很漠然，假如韦达有刘高兴的肾，绝不会如此。刘高兴为了盖新房、娶媳妇，卖过三次血，听说有人卖血得了乙肝，才不卖血卖了肾，卖肾的钱盖起了新房，但新房盖起来了，那女的却嫁给了别人，为此，他吹了三天三夜的箫，卖了一双女式尖头高跟鞋，来到城里，要娶城里的女人做老婆。贾平凹说:我这么安排，是想表达他与城市的关系，刘高兴是无法融入这个城市的。刘高兴的命运也就是农民工的命运。大部分农民就死了回去了，只有他还在这留着，最后的处理是让五富留着鬼魂在城里，但刘高兴还在城里，他在这个城里还有他的梦想，他还觉得他的肾脏还在城里，换作城里人的。他把肾脏卖给城里人，他就觉得他是城里人，而实际上那个城里人换的是肝。但在刘高兴的脑子里觉得自己的肾脏还在城里，而且在城里还有他一个女人。他有各种的理想和追求，他的想像还在城里，他离不开城里。刘高兴留在城里，带着残缺的、只有一个肾的身体，另一个肾卖给了城里人，成为城里人的先天之本，融入了城市，农村的肾养活着城市，原来，城市的一半是农村。但刘高兴不知道，卖掉的肾长在谁的身体里，离开了自己，就是别人的了，是城里的了，与自己无关。只有一个肾的刘高兴留在城里，依然高兴着，他将来会怎么样，刘高兴不知道，贾平凹也不知道。答案在时间和城乡历史的眼睛里。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                刘高兴用身份证帮助教授开门，换来了对他的道德怀疑。面对文化知识和道德质疑的层面，刘高兴无法势均力敌。顽强的做城市人的意愿和乡下人身份的冲突，构成其无法回避的行为与人格矛盾。面对城市和破烂族群内的人，刘高兴拥有双重身份。他成功地让&quot;五富只要和黄八在一起，言必称我刘高兴&quot;，依凭比五富、黄八充分的现代知识文化，树立起在破烂族群内的权威。开导五富体现他领导权的实现过程，但他不能反省不自觉地为城市说话的立场，他是在城市规制下建构主体自我意识。他有情智分裂的倾向除了情感上的联系，理智上他却瞧不起同伴，自问&quot;刘高兴，你还讲究有文化，完全把自己混成个五富或黄八了么&quot;时刻注意提醒自己与同伴的分别，这与城市人瞧不起乡下人是同质问题。日渐城市化的刘高兴，是否最终和两三代之前城市化的人们一样，瞧不起未曾城市化的乡下同胞刘高兴以抗争方式实现与城市的和解，不知不觉地仍然作了成规的俘虏，甚至不乏精神胜利的意味。他进宾馆收破烂，被保安阻止，脱了鞋才得以进人。但他能借想象驱散被身份成规压迫的屈辱，竟然幻想留在大堂的脚印能够自由地到处游走。他穿上皮鞋、西装去为翠花讨回身份证，让五富称呼他刘处长而不是刘局长，想象自己在行政制度中适宜的级别。珍藏的那双高跟鞋代表他对城市女性的想象，而不考虑乡村大脚骨翠花。他和石热闹在一起，更多体现为一种居领导地位的道德优越感，优越感出发点除个人尊严以外，只是为自己更能被城市所接受。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                农民工大多也是比较满足的。如五富把一天挣一几块钱、一口萝卜丝儿一口馍，再喝一阵稀饭&quot;的日子视为好日子，他说:&quot;清风镇没几个人像咱这日子哩!&quot;农民工们普遍认为城里人看不起他们，但是他们都不愿回农村去过缺吃少穿的日子。对城市生活的满足是建立在与从前农村生活的比较上，这一方面说明了农村生活已经对农民失去了吸引力，无法忍受的贫穷和对城市生活的向往让农民毅然离开土地。另一方面也隐藏了不能横向对比、知足常乐的意思。如果同其他城里人比较，农民很可能对城市失望、怨恨甚至起破坏之心。像刘高兴那样不计付出、以苦为乐，把整个生命献给城市的人，确实是很少见的。在城市中受尽了欺侮、蔑视后，五富和黄八咒骂现实和城市，以此作为回应。而刘高兴、孟夷纯和杏胡则以不同的方式进行抗争，试图改变悲惨的现状。刘高兴干过收购医疗垃圾的违法行为，以此谋取暴利。孟夷纯并不是一开始就以出卖身体为生，刚来到城市时，她在饭店做过洗碗工，当过保姆，但收入微薄，勉强维持生计。为了帮助弟弟破案，她不得不成为妓女，赚足钱才会给公安局去调查罪犯。杏胡在经历丧夫之痛后没有自寻死路，而是给人生制定了计划，并从中收获不少。虽然他们的抗争都起到了一定的成效，但都以种种原因，最终以失败告终。刘高兴收购医疗垃圾获得了不少利润，但后来被制止。孟夷纯做了妓女之后，攒了很多钱，但是警察的无休止的索要，让孟夷纯无法摆脱妓女的身份，陷入弟弟与自我救赎中无法自拔。杏胡的&quot;计划&quot;让刘高兴上受益匪浅，但是在城市意识形态下，杏胡以自身的能力，难以通过正当的手段来实现计划，无奈走上收购&quot;赃物&quot;的犯罪道路，最终被捕。</p>
                        </div>
                        <h3 style="margin: 20px 0px 12px; padding: 0px 0px 12px; font-size: 14px; font-weight: 500; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative; border-bottom: 1px solid rgb(236, 236, 236); cursor: pointer; line-height: 18px; overflow: hidden;"><a class="anchor" name="1953729-2067635-4_2" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h3-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><b class="title" style="font-weight: 500; color: rgb(51, 51, 51); float: left; font-size: 18px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif;">艺术手法</b></h3>
                        <div class="h3_content" style="margin: 0px; padding: 0px;">
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                贾平凹为叙述层次丰富起来，尽一切能力去抑制，虚空高蹈的叙述，使故事更加生活化、细节化、变得柔和温暖。五富扯着刘高兴衣襟走进西安城，个月城市生活就让他丢了性命。五富随着高兴住进&quot;城中村&quot;池头村，从来不离开自己的地盘兴隆街，只走&quot;兴隆街一废品收购点一池头村&quot;三点一线的路，也不会独自从西安回家。他执著乡下的粮食观念，饭食一点不剩，却不会自己保藏或者邮寄收卖破烂挣来的钱。他不懂也不愿接受城市规制，不明白为什么乡下的北瓜被叫做南瓜，&quot;鸡爪&quot;叫成&quot;凤爪&quot;。他没有刘高兴&quot;小草不自卑&quot;的态度，永远只顾眼下的微末机会。《高兴》中的生活细节真切，趣味却得归诸差异叙述美学。叙述中首先包含对照木呐如闰土的五富，只能被生活俘获，永远做不了主人，甚至不会像黄八那样诅咒权势刘高兴与他最大的差别在于想象力，凭想象超越生活境遇。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                《高兴》与一般乡下人进城叙事的不同，在于主体的自觉反思。乡下人&quot;刘哈娃&quot;自己更名&quot;刘高兴&quot;，表现自我主宰的意愿，自我主宰和被主宰之间的张力，演绎着反抗成规的斗争。命名的特殊行为在一个特殊的语境中被质疑其合法性。小说开头用两个无主句展现审查、被审查的话语权力控制场面。尊严的警察惜语如金地审问&quot;名字&quot;轻蔑地把&quot;你叫什么名字&quot;的双边对话省略成一个无主句。被审查者堂堂正正自称刘高兴，而不屑于完整回答我的名字是，内心抗拒的潜台词是&quot;凭什么要比你多说几个字&quot;看似旗鼓相当的较量，乡下人进城的一种叙述潜藏的是进城农民自我命名合法性遭到质疑，刘高兴的不怯为乡下人所少有，他坚持不同于身份证上的新命名。名字是符号，指征的是主体建构。同伴五富虽然习惯了称呼他为&quot;刘高兴&quot;，但自己没有重新自我命名的意愿，也不明白这是要祛除乡下人的文化烙印和城市新生活的开端。刘高兴背五富尸体还乡的情境成了个寓言。五富死后还乡的意愿是乡土认同的特殊方式，意愿变成行动则有违城市规则，它必须受城市的规制。违规的&quot;背尸&quot;引发了对背尸者自我更名合法性的审查。警察在其坚持下终于叫他刘高兴-虽然被手铐拘执，刘高兴还是胜利了。刘高兴是个矛盾聚合体。他执行五富遗愿，客观上强化了生命之根的乡土认同与做一个城市人的志愿之间的冲突。他改了名字，有一副与城市人无别的外形，却改变不了乡下人身份。刘高兴乡下人进城的&quot;越境迁移，难以穿越的是歧视性文化空间，难以更替的是历史深远的城乡意识形态，的规划约束。乡下人进城难以摆脱&quot;他者地位，韦达一伙成功者吃素，满座只为高兴和五富添加荤菜，尊重的表象下面是知识文化层面的鄙夷-只有穷人、愚人还嗜荤。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                《高兴》中刘高兴在多重成规之下的主体建构，是一个充满矛盾冲突的艰难过程。他重新自我命名的&quot;高兴&quot;，无论作为形容词还是作为动词，主要的意涵是愉快而兴奋，是一种对城市的示好。文中通过怀疑&quot;高兴&quot;的方式求之于正义、平等的力度。&quot;背尸还乡&quot;喻指其乡村根性，解构了&quot;高兴&quot;命名的价值意义，这或许是《高兴》的最大价值。二元体制分割的城乡矛盾，因乡下人进城而变成了同一空间内人的矛盾，乡下人与城里人的矛盾演绎成形形色色的生存冲突。明知无法与城市人分割原本由父兄创造而被提取到城市中来的利益，他们只好在城市人无意进人的空间里谋生存、成为特殊族群破烂族群、民工族群、杂工族群。贾平凹期望从&quot;拾破烂的群体&quot;的&quot;生存状态和精神状态里触摸出这个年代城市的不轻易能触摸到的&quot;脉搏&quot;小说叙述与社会学研究有别。后者聚焦于由&quot;农家女&quot;到&quot;打工妹&quot;的集合概念，在统计与个案研究的方法统摄下，对生命与身体相当忽视。小说叙述更多瞩目孟夷纯、米谷那样的女性生命群体，并且，小说最后以刘高兴痛苦凄惨的生活状态而结尾，更是与文章的主题思想相呼应。</p>
                        </div>
                    </div>
                    <h2 style="margin: 35px 0px 15px -30px; padding: 0px; font-size: 22px; font-weight: 500; border-left: 10px solid rgb(55, 171, 47); line-height: 22px; text-indent: 20px; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative;"><a name="1953729-2067635-5" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h2-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><span class="opt js-edittext" style="border-right: 1px solid rgb(217, 217, 217); float: right; font-size: 12px; font-family: simsun; margin-right: 6px; padding-right: 7px;"><a class="edit" data-log="edit-title" href="https://baike.so.com/create/edit/?eid=1953729&amp;sid=2067635&amp;secid=5" style="color: rgb(49, 152, 24); text-decoration: none;"><i class="ico" style="font-style: italic; background-image: url(&quot;https://p.ssl.qhmsg.com/t01c067b7271a91a2e3.png&quot;); background-repeat: no-repeat; display: inline-block; height: 16px; vertical-align: -5px; width: 16px; background-position: 0px -40px;"></i>编辑本段</a></span><b class="title" style="font-weight: 500; color: rgb(0, 0, 0); float: left; font-size: 22px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; line-height: 24px; zoom: 1;">作品评价</b></h2>
                    <div class="sonConBox " style="margin: 0px; padding: 0px; color: rgb(51, 51, 51);">
                        <div class="h2_content" style="margin: 0px; padding: 0px;">
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                这是一部反映现实题材的小说，是一部反映当代农民的小说，也注定是一部令人心情沉重的小说。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                ----搜狐新闻评价</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                贾平凹的《高兴》为什么令人心情沉重?是城乡不和谐令人沉重。在大都市里，我们看多了一个庆典几千万，一个晚会上百万，到处张扬着盛世的繁荣，或许从这些破烂王的生存状态和精神状态里能摸出这个年代城市不轻易能触摸到的脉搏&quot;。 --文学家马祥</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                贾平凹说他在城市生活了几十年，但骨子里还是个农民。他的多数作品也是以农民为主的。《高兴》坚持了贾平凹对农民的一贯关注，写流落都市的拾荒者的命运，这事实上也是写进城农民的命运。他们都有一个共同的特点:在城市中艰难地生存。贾平凹不光写了他们的物质层面，他也写到了他们的精神层面。随着城市现代化进程的加快，城市人正日益物质化，而精神层面的追求却一天天减少，这也正是现代化进程中所最可怕的。贾平凹深刻地反映了这一点，他所具有的忧患意识让人感动。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                贾平凹写出了一份留给历史的社会记录，他的《高兴》因此无论如何让人高兴不起来。(山东大学徐晓教授)</p>
                        </div>
                    </div>
                    <h2 style="margin: 35px 0px 15px -30px; padding: 0px; font-size: 22px; font-weight: 500; border-left: 10px solid rgb(55, 171, 47); line-height: 22px; text-indent: 20px; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative;"><a name="1953729-2067635-6" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h2-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><span class="opt js-edittext" style="border-right: 1px solid rgb(217, 217, 217); float: right; font-size: 12px; font-family: simsun; margin-right: 6px; padding-right: 7px;"><a class="edit" data-log="edit-title" href="https://baike.so.com/create/edit/?eid=1953729&amp;sid=2067635&amp;secid=6" style="color: rgb(49, 152, 24); text-decoration: none;"><i class="ico" style="font-style: italic; background-image: url(&quot;https://p.ssl.qhmsg.com/t01c067b7271a91a2e3.png&quot;); background-repeat: no-repeat; display: inline-block; height: 16px; vertical-align: -5px; width: 16px; background-position: 0px -40px;"></i>编辑本段</a></span><b class="title" style="font-weight: 500; color: rgb(0, 0, 0); float: left; font-size: 22px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; line-height: 24px; zoom: 1;">作品影响</b></h2>
                    <div class="sonConBox " style="margin: 0px; padding: 0px; color: rgb(51, 51, 51);">
                        <div class="h2_content" style="margin: 0px; padding: 0px;">
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                2014年8月18日，由瑞典翻译家、汉学家陈安娜女士翻译的中国著名作家贾平凹的长篇小说《高兴》在瑞典出版。</p>
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                在读过瑞典文版的《高兴》之后，陈安娜的老师马悦然专门向其发来邮件表达了自己的赞赏之情，并将《高兴》一书和美国作家、诺贝尔文学奖得主约翰·斯坦贝克1937年发表的作品《老鼠与人》做对比。</p>
                        </div>
                    </div>
                    <h2 style="margin: 35px 0px 15px -30px; padding: 0px; font-size: 22px; font-weight: 500; border-left: 10px solid rgb(55, 171, 47); line-height: 22px; text-indent: 20px; clear: both; font-family: &quot;microsoft yahei&quot;; position: relative;"><a name="1953729-2067635-7" style="color: rgb(19, 110, 194); text-decoration: none; position: absolute; top: -10px;"></a><a class="conArrow" data-logid="h2-title" href="https://baike.so.com/doc/1953729-2067635.html#" style="color: transparent; text-decoration: none; background: url(&quot;https://p.ssl.qhmsg.com/t012b40d58f262241ac.png&quot;) 0px 0px no-repeat; display: inline; float: right; font-size: 0px; height: 20px; text-shadow: none; width: 20px;">折叠</a><span class="opt js-edittext" style="border-right: 1px solid rgb(217, 217, 217); float: right; font-size: 12px; font-family: simsun; margin-right: 6px; padding-right: 7px;"><a class="edit" data-log="edit-title" href="https://baike.so.com/create/edit/?eid=1953729&amp;sid=2067635&amp;secid=7" style="color: rgb(49, 152, 24); text-decoration: none;"><i class="ico" style="font-style: italic; background-image: url(&quot;https://p.ssl.qhmsg.com/t01c067b7271a91a2e3.png&quot;); background-repeat: no-repeat; display: inline-block; height: 16px; vertical-align: -5px; width: 16px; background-position: 0px -40px;"></i>编辑本段</a></span><b class="title" style="font-weight: 500; color: rgb(0, 0, 0); float: left; font-size: 22px; font-family: &quot;microsoft yahei&quot;, Arial, Helvetica, sans-serif; line-height: 24px; zoom: 1;">作者简介</b></h2>
                    <div class="sonConBox " style="margin: 0px; padding: 0px; color: rgb(51, 51, 51);">
                        <div class="h2_content" style="margin: 0px; padding: 0px;">
                            <p style="margin: 0px 0px 15px; padding: 0px; line-height: 24px; text-indent: 2em; zoom: 1; color: rgb(51, 51, 51);">
                                <a href="https://baike.so.com/doc/1686928-1783799.html" style="color: rgb(19, 110, 194); text-decoration: none;" target="_blank">贾平凹</a>(wā)，陕西作协主席，中国书协会员，当代著名作家。贾平凹是我国当代文坛屈指可数的文学大家和文学奇才，是一位当代中国最具叛逆性、最富创造精神和广泛影响的具有世界意义的作家，也是当代中国可以进入中国和世界文学史册的为数不多的著名文学家之一。被誉为&quot;鬼才&quot;。代表作有长篇小说《商州》、《浮躁》、《废都》、《白夜》、《秦腔》、《<a href="https://baike.so.com/doc/5330851-5566025.html" style="color: rgb(19, 110, 194); text-decoration: none;" target="_blank">古炉</a>》等，曾多次获文学大奖。作品《我不是个好儿子》选入鲁教版语文必修三、作品《<a href="https://baike.so.com/doc/5354646-5590110.html" style="color: rgb(19, 110, 194); text-decoration: none;" target="_blank">月迹</a>》已选入苏教版语文课本、作品《落叶》入选北师大版和鲁教版中学教材。</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form id="form1" runat="server">
    <div>
    
    </div>
    </form>
</body>
</html>
